### ISSUE TITLE
Kicking off

### ISSUE THREAD

**Issue by henriquea** [henriquea/module-health#1]
I tend to use `npm view` to give me information about a module but read the output is tedious. The idea here is to give a short summary about the module, how "health" the module is.

There are a few key things I like to know before decide which module include in my project:

- Number of dependencies – the less, the merrier
- Last time modified
- Number of versions – kinda help to know how often a new version is published?
- Is the project outdated?

That's it!

**Comment by henriquea** [comment]
Another thought, this could work as an API so any tool could hook up.

```js
import moduleHealth from 'module-health';

moduleHealth('js-yamk')
  .then( ... )
```

Probably not worth the effort.

cc @rafaelrinaldi

**Comment by rafaelrinaldi** [comment]
@henriquea I think the key question to answer is what is the output here. What measurements are going to be used to say if a module is _healthy_ or not. There are tools already available like `npm-check` and `slow-deps` that already do a good job at giving maintainers a good overview about their application, so should you aim for a _master overview_ type of thing that just combines these tools?

**Comment by henriquea** [comment]
@rafaelrinaldi cool! I'll have a look again at `npm-check` I'm already using `slow-deps`. It's great but only gives the number of deps. I think the name is wrong because there is no way to check if a component is *healthy* or not.
